spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-service-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.OrderService.kafka.dto.PaymentEvent
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

external:
  user-service:
    url: ${EXTERNAL_USER_SERVICE_URL}